### ISSUE TITLE
/shoutoutcs is visible and times out

### ISSUE THREAD

**Issue by SteveDuitsman** [SafeNetConsulting-Milwaukee/company-hub-shoutout#22]
`/shoutoutcs @jackkoppa for being awesome` causes a timeout.

`*/shoutoutcs @jackkoppa for being awesome* failed with the error "operation_timeout"`

As an aside, it seems like this shouldnt be visible?

**Comment by jackkoppa** [comment]
Intended to be visible, and tracked in https://github.com/SafeNetConsulting-Milwaukee/company-hub-shoutout-csharp. Pretty excited about the dual-language, dual-build-pipelines aspect of development. 

I'll close this here, and for now not open another issue in the C# repo, since it's still under development, and the timeout is a known issue. @SteveDuitsman, @tpenland
