### ISSUE TITLE
Add build step to configure app settings for storage on the deployed function

### ISSUE THREAD

**Issue by jjr2527** [SafeNetConsulting-Milwaukee/company-hub-shoutout#9]
Currently we need to configure the table storage connection info as app settings on the azure function.

We need a way of automating configuring the app settings as part of the deployment.

**Comment by jackkoppa** [comment]
Grabbing this from @jjr2527, because I think I found the solution [here](https://serverless.com/framework/docs/providers/aws/guide/variables#recursively-reference-properties), where it seems you can set environment vars on a per-provider basis. That, combined with the syntax for referencing *current* environment vars [here](https://serverless.com/framework/docs/providers/aws/guide/variables#referencing-environment-variables), should be enough to set once (in Travis-CI), and push to anywhere

**Comment by jackkoppa** [comment]
Attempting this in 41e4ce8

**Comment by jackkoppa** [comment]
![partial_env_var_passing_success](https://user-images.githubusercontent.com/14101491/38779951-4a1c50d4-4095-11e8-939e-8d14943a7622.PNG)

First attempt, from 41e4ce8, seems like a partial success, but didn't pass the full value. Will try building again with re-setting that var in Travis

**Comment by jackkoppa** [comment]
Verified fix after [Travis-CI build 21](https://travis-ci.org/SafeNetConsulting-Milwaukee/company-hub-shoutout/builds/366820027), from https://github.com/SafeNetConsulting-Milwaukee/company-hub-shoutout/commit/b4fbf74bb92b9c5d5bdc7054ba3576fcc4b25c83. Now setting the 2 separate environment vars - a recommended option on the [Table Storage docs](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-nodejs#add-an-azure-storage-connection), to avoid the cut-off issue at the semicolon in `AZURE_STORAGE_CONNECTION_STRING`
